cluster:
  name: ${CLUSTER_NAME}

node:
  data: true

network:
  host: 0.0.0.0

cloud:
  kubernetes:
    service: ${SERVICE_DNS}
    namespace: default

discovery:
  type: kubernetes
  zen.ping.multicast.enabled: false

bootstrap:
  mlockall: true

http:
  enabled: true

# Otherwise kubernetes plugin doesn't work on ES 2.0
security.manager.enabled: false
