cluster:
  name: ${CLUSTER_NAME}

node:
  data: ${NODE_DATA}

network:
  host: _non_loopback:ipv4_

cloud:
  kubernetes:
    service: ${SERVICE_DNS}
    namespace: default

discovery:
  type: kubernetes
  zen.ping.multicast.enabled: false

bootstrap:
  mlockall: true

http:
  enabled: {HTTP_ENABLED}

# Otherwise kubernetes plugin doesn't work on ES 2.0
security.manager.enabled: false
