cluster:
  name: ${CLUSTER_NAME}

node:
  data: true

cloud:
  k8s:
    servicedns: ${SERVICE_DNS}
  kubernetes:
    servicedns: ${SERVICE_DNS}
    service: ${SERVICE_DNS}
    namespace: default

discovery:
  type: kubernetes
  zen.ping.multicast.enabled: false

bootstrap:
  mlockall: true

http:
  enabled: true

# path:
#   data: /data
